// ============================================================
// EXAM CONFIG — Central source of ALL exam presets
// This is REFERENCE ONLY. Users always enter their own values.
// Update this file when new notifications are released.
// ============================================================

export const EXAM_CATEGORIES = {
  SSC: "SSC Exams",
  BANK: "Bank Exams",
  RAILWAY: "Railway Exams",
  UPSC: "UPSC / PSC",
  ENTRANCE: "Entrance Exams",
  STATE: "State Exams",
};

export const EXAMS = [
  {
    id: "ssc-cgl",
    slug: "ssc-cgl-photo-size",
    name: "SSC CGL",
    fullName: "SSC Combined Graduate Level",
    category: "SSC",
    lastVerified: "April 2026",
    officialSite: "https://ssc.nic.in",
    photo: {
      maxSizeKB: 50,
      minSizeKB: 20,
      widthPx: 200,
      heightPx: 230,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Colour passport size photo with white background",
    },
    signature: {
      maxSizeKB: 20,
      minSizeKB: 10,
      widthPx: 140,
      heightPx: 60,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Signature on white paper with black/blue ink",
    },
  },
  {
    id: "ssc-chsl",
    slug: "ssc-chsl-photo-size",
    name: "SSC CHSL",
    fullName: "SSC Combined Higher Secondary Level",
    category: "SSC",
    lastVerified: "April 2026",
    officialSite: "https://ssc.nic.in",
    photo: {
      maxSizeKB: 50,
      minSizeKB: 20,
      widthPx: 200,
      heightPx: 230,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Colour passport size photo with white background",
    },
    signature: {
      maxSizeKB: 20,
      minSizeKB: 10,
      widthPx: 140,
      heightPx: 60,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Signature on white paper",
    },
  },
  {
    id: "ssc-mts",
    slug: "ssc-mts-photo-size",
    name: "SSC MTS",
    fullName: "SSC Multi Tasking Staff",
    category: "SSC",
    lastVerified: "April 2026",
    officialSite: "https://ssc.nic.in",
    photo: {
      maxSizeKB: 50,
      minSizeKB: 20,
      widthPx: 200,
      heightPx: 230,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Recent passport size photograph",
    },
    signature: {
      maxSizeKB: 20,
      minSizeKB: 10,
      widthPx: 140,
      heightPx: 60,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Signature in running hand",
    },
  },
  {
    id: "ibps-po",
    slug: "ibps-po-photo-size",
    name: "IBPS PO",
    fullName: "IBPS Probationary Officer",
    category: "BANK",
    lastVerified: "April 2026",
    officialSite: "https://ibps.in",
    photo: {
      maxSizeKB: 100,
      minSizeKB: 20,
      widthPx: 200,
      heightPx: 230,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Recent passport size photo, not more than 6 months old",
    },
    signature: {
      maxSizeKB: 50,
      minSizeKB: 10,
      widthPx: 140,
      heightPx: 60,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Signature in full, not initials",
    },
  },
  {
    id: "ibps-clerk",
    slug: "ibps-clerk-photo-size",
    name: "IBPS Clerk",
    fullName: "IBPS Clerk Recruitment",
    category: "BANK",
    lastVerified: "April 2026",
    officialSite: "https://ibps.in",
    photo: {
      maxSizeKB: 100,
      minSizeKB: 20,
      widthPx: 200,
      heightPx: 230,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Recent colour passport size photograph",
    },
    signature: {
      maxSizeKB: 50,
      minSizeKB: 10,
      widthPx: 140,
      heightPx: 60,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Full signature, not initials",
    },
  },
  {
    id: "sbi-po",
    slug: "sbi-po-photo-size",
    name: "SBI PO",
    fullName: "State Bank of India Probationary Officer",
    category: "BANK",
    lastVerified: "April 2026",
    officialSite: "https://sbi.co.in/careers",
    photo: {
      maxSizeKB: 100,
      minSizeKB: 20,
      widthPx: 200,
      heightPx: 230,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Passport size photo, colour, recent",
    },
    signature: {
      maxSizeKB: 50,
      minSizeKB: 10,
      widthPx: 140,
      heightPx: 60,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Signature in blue or black ink",
    },
  },
  {
    id: "rrb-ntpc",
    slug: "rrb-ntpc-photo-size",
    name: "RRB NTPC",
    fullName: "Railway Recruitment Board NTPC",
    category: "RAILWAY",
    lastVerified: "April 2026",
    officialSite: "https://indianrailways.gov.in",
    photo: {
      maxSizeKB: 100,
      minSizeKB: 20,
      widthPx: 200,
      heightPx: 230,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Recent passport size colour photo",
    },
    signature: {
      maxSizeKB: 50,
      minSizeKB: 10,
      widthPx: 140,
      heightPx: 60,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Candidate's own signature",
    },
  },
  {
    id: "rrb-group-d",
    slug: "rrb-group-d-photo-size",
    name: "RRB Group D",
    fullName: "Railway Recruitment Board Group D",
    category: "RAILWAY",
    lastVerified: "April 2026",
    officialSite: "https://indianrailways.gov.in",
    photo: {
      maxSizeKB: 100,
      minSizeKB: 20,
      widthPx: 200,
      heightPx: 230,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Passport size photo with white background",
    },
    signature: {
      maxSizeKB: 50,
      minSizeKB: 10,
      widthPx: 140,
      heightPx: 60,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Handwritten signature",
    },
  },
  {
    id: "upsc-cse",
    slug: "upsc-photo-size",
    name: "UPSC CSE",
    fullName: "UPSC Civil Services Examination",
    category: "UPSC",
    lastVerified: "April 2026",
    officialSite: "https://upsc.gov.in",
    photo: {
      maxSizeKB: 300,
      minSizeKB: 20,
      widthPx: 300,
      heightPx: 350,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Recent passport size photo, plain white background",
    },
    signature: {
      maxSizeKB: 300,
      minSizeKB: 20,
      widthPx: 300,
      heightPx: 100,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Signature on white paper",
    },
  },
  {
    id: "jee-main",
    slug: "jee-main-photo-size",
    name: "JEE Main",
    fullName: "Joint Entrance Examination Main",
    category: "ENTRANCE",
    lastVerified: "April 2026",
    officialSite: "https://jeemain.nta.ac.in",
    photo: {
      maxSizeKB: 300,
      minSizeKB: 10,
      widthPx: 200,
      heightPx: 230,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Passport size colour photograph, white/off-white background",
    },
    signature: {
      maxSizeKB: 30,
      minSizeKB: 4,
      widthPx: 160,
      heightPx: 60,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Candidate signature on white paper",
    },
  },
  {
    id: "neet",
    slug: "neet-photo-size",
    name: "NEET UG",
    fullName: "National Eligibility cum Entrance Test UG",
    category: "ENTRANCE",
    lastVerified: "April 2026",
    officialSite: "https://neet.nta.nic.in",
    photo: {
      maxSizeKB: 200,
      minSizeKB: 10,
      widthPx: 200,
      heightPx: 230,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Passport size photo, white background, colour",
    },
    signature: {
      maxSizeKB: 30,
      minSizeKB: 4,
      widthPx: 160,
      heightPx: 60,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Signature in black or blue ink on white paper",
    },
  },
  {
    id: "cuet",
    slug: "cuet-photo-size",
    name: "CUET",
    fullName: "Common University Entrance Test",
    category: "ENTRANCE",
    lastVerified: "April 2026",
    officialSite: "https://cuet.nta.nic.in",
    photo: {
      maxSizeKB: 300,
      minSizeKB: 10,
      widthPx: 200,
      heightPx: 230,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Recent passport photograph, plain background",
    },
    signature: {
      maxSizeKB: 30,
      minSizeKB: 4,
      widthPx: 160,
      heightPx: 60,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Candidate's signature",
    },
  },

  // ============================================================
  // SESSION 2 ADDITIONS — 10 more exams
  // ============================================================
  {
    id: "ssc-cpo",
    slug: "ssc-cpo-photo-size",
    name: "SSC CPO",
    fullName: "SSC Central Police Organisations",
    category: "SSC",
    lastVerified: "April 2026",
    officialSite: "https://ssc.nic.in",
    photo: {
      maxSizeKB: 50,
      minSizeKB: 20,
      widthPx: 200,
      heightPx: 230,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Passport size colour photo, white background",
    },
    signature: {
      maxSizeKB: 20,
      minSizeKB: 10,
      widthPx: 140,
      heightPx: 60,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Signature on white paper in black ink",
    },
  },
  {
    id: "ssc-gd",
    slug: "ssc-gd-photo-size",
    name: "SSC GD Constable",
    fullName: "SSC General Duty Constable",
    category: "SSC",
    lastVerified: "April 2026",
    officialSite: "https://ssc.nic.in",
    photo: {
      maxSizeKB: 50,
      minSizeKB: 20,
      widthPx: 200,
      heightPx: 230,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Recent passport photo with white background",
    },
    signature: {
      maxSizeKB: 20,
      minSizeKB: 10,
      widthPx: 140,
      heightPx: 60,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Candidate's signature in running hand",
    },
  },
  {
    id: "nda",
    slug: "nda-photo-size",
    name: "NDA",
    fullName: "National Defence Academy",
    category: "UPSC",
    lastVerified: "April 2026",
    officialSite: "https://upsc.gov.in",
    photo: {
      maxSizeKB: 300,
      minSizeKB: 20,
      widthPx: 300,
      heightPx: 350,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Passport size colour photo, white background, recent",
    },
    signature: {
      maxSizeKB: 300,
      minSizeKB: 20,
      widthPx: 300,
      heightPx: 100,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Signature in full, not initials",
    },
  },
  {
    id: "cds",
    slug: "cds-photo-size",
    name: "CDS",
    fullName: "Combined Defence Services",
    category: "UPSC",
    lastVerified: "April 2026",
    officialSite: "https://upsc.gov.in",
    photo: {
      maxSizeKB: 300,
      minSizeKB: 20,
      widthPx: 300,
      heightPx: 350,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Recent colour passport size photo",
    },
    signature: {
      maxSizeKB: 300,
      minSizeKB: 20,
      widthPx: 300,
      heightPx: 100,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Signature on plain white paper",
    },
  },
  {
    id: "cisf-ac",
    slug: "cisf-ac-photo-size",
    name: "CISF AC",
    fullName: "CISF Assistant Commandant",
    category: "UPSC",
    lastVerified: "April 2026",
    officialSite: "https://upsc.gov.in",
    photo: {
      maxSizeKB: 300,
      minSizeKB: 20,
      widthPx: 300,
      heightPx: 350,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Passport size photo with white background",
    },
    signature: {
      maxSizeKB: 300,
      minSizeKB: 20,
      widthPx: 300,
      heightPx: 100,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Full signature on white paper",
    },
  },
  {
    id: "sbi-clerk",
    slug: "sbi-clerk-photo-size",
    name: "SBI Clerk",
    fullName: "State Bank of India Junior Associates",
    category: "BANK",
    lastVerified: "April 2026",
    officialSite: "https://sbi.co.in/careers",
    photo: {
      maxSizeKB: 100,
      minSizeKB: 20,
      widthPx: 200,
      heightPx: 230,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Recent passport size photo with white background",
    },
    signature: {
      maxSizeKB: 50,
      minSizeKB: 10,
      widthPx: 140,
      heightPx: 60,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Signature in blue or black ink",
    },
  },
  {
    id: "rbi-grade-b",
    slug: "rbi-grade-b-photo-size",
    name: "RBI Grade B",
    fullName: "Reserve Bank of India Grade B Officer",
    category: "BANK",
    lastVerified: "April 2026",
    officialSite: "https://rbi.org.in",
    photo: {
      maxSizeKB: 100,
      minSizeKB: 20,
      widthPx: 200,
      heightPx: 230,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Passport size colour photo with white background",
    },
    signature: {
      maxSizeKB: 50,
      minSizeKB: 10,
      widthPx: 140,
      heightPx: 60,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Signature on white paper",
    },
  },
  {
    id: "lic-aao",
    slug: "lic-aao-photo-size",
    name: "LIC AAO",
    fullName: "LIC Assistant Administrative Officer",
    category: "BANK",
    lastVerified: "April 2026",
    officialSite: "https://licindia.in",
    photo: {
      maxSizeKB: 100,
      minSizeKB: 20,
      widthPx: 200,
      heightPx: 230,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Recent colour passport size photograph",
    },
    signature: {
      maxSizeKB: 50,
      minSizeKB: 10,
      widthPx: 140,
      heightPx: 60,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Signature in black or blue ink",
    },
  },
  {
    id: "mpsc",
    slug: "mpsc-photo-size",
    name: "MPSC",
    fullName: "Maharashtra Public Service Commission",
    category: "STATE",
    lastVerified: "April 2026",
    officialSite: "https://mpsc.gov.in",
    photo: {
      maxSizeKB: 100,
      minSizeKB: 20,
      widthPx: 200,
      heightPx: 230,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Passport size colour photo, white background",
    },
    signature: {
      maxSizeKB: 50,
      minSizeKB: 10,
      widthPx: 140,
      heightPx: 60,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Candidate's signature",
    },
  },
  {
    id: "uppsc",
    slug: "uppsc-photo-size",
    name: "UPPSC",
    fullName: "Uttar Pradesh Public Service Commission",
    category: "STATE",
    lastVerified: "April 2026",
    officialSite: "https://uppsc.up.nic.in",
    photo: {
      maxSizeKB: 100,
      minSizeKB: 20,
      widthPx: 200,
      heightPx: 230,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Colour passport size photo, white or light background",
    },
    signature: {
      maxSizeKB: 50,
      minSizeKB: 10,
      widthPx: 140,
      heightPx: 60,
      format: ["JPG", "JPEG"],
      background: "White",
      notes: "Signature in black ink on white paper",
    },
  },
];

// Get exam by slug
export const getExamBySlug = (slug) =>
  EXAMS.find((e) => e.slug === slug) || null;

// Get exams by category
export const getExamsByCategory = (category) =>
  EXAMS.filter((e) => e.category === category);

// All slugs for routing
export const getAllSlugs = () => EXAMS.map((e) => e.slug);

// ============================================================
// SESSION 2 ADDITIONS — 10 more exams
// ============================================================
